// conflicts-data.js — CONFLICTWATCH Historical Conflict Database
// 75+ major conflicts, 1975-2025, curated and verified

window.HISTORICAL_CONFLICTS = [
  // ============================================================
  // EUROPE
  // ============================================================
  {
    id: 1,
    name: "Ukraine-Russia War",
    country: "Ukraine / Russia",
    region: "Europe",
    lat: 49.4, lng: 32.0,
    startYear: 2022, endYear: null,
    type: "Interstate War",
    fatalities: 500000,
    severity: 5,
    description: "Russia launched a full-scale invasion of Ukraine on February 24, 2022, following the 2014 annexation of Crimea and Donbas conflict. The war has caused catastrophic casualties, mass displacement of over 8 million people, and widespread destruction across Ukrainian cities and infrastructure.",
    parties: ["Russia", "Ukraine", "NATO (support)"],
    status: "Ongoing"
  },
  {
    id: 2,
    name: "Donbas Conflict",
    country: "Ukraine",
    region: "Europe",
    lat: 47.9, lng: 37.6,
    startYear: 2014, endYear: 2022,
    type: "Civil War",
    fatalities: 14000,
    severity: 3,
    description: "Armed conflict in eastern Ukraine between Ukrainian forces and Russian-backed separatists in the Donetsk and Luhansk regions following Russia's annexation of Crimea. The conflict simmered for eight years before escalating into the full-scale invasion of 2022.",
    parties: ["Ukraine", "DPR", "LPR", "Russia"],
    status: "Ended"
  },
  {
    id: 3,
    name: "Yugoslav Wars",
    country: "Former Yugoslavia",
    region: "Europe",
    lat: 44.5, lng: 18.0,
    startYear: 1991, endYear: 2001,
    type: "Civil War",
    fatalities: 140000,
    severity: 5,
    description: "A series of ethnic conflicts and wars of independence that accompanied the breakup of Yugoslavia, encompassing the Ten-Day War, Croatian War, Bosnian War, Kosovo War, and the insurgency in North Macedonia. Ethnic cleansing and the Srebrenica genocide marked the worst atrocities in Europe since WWII.",
    parties: ["Serbia", "Croatia", "Bosnia", "Slovenia", "Kosovo", "NATO"],
    status: "Ended"
  },
  {
    id: 4,
    name: "First Chechen War",
    country: "Russia",
    region: "Europe",
    lat: 43.3, lng: 45.7,
    startYear: 1994, endYear: 1996,
    type: "Civil War",
    fatalities: 50000,
    severity: 4,
    description: "Russia launched a military campaign to prevent Chechnya's secession, resulting in intense urban warfare in Grozny. Russian forces suffered unexpected defeats before a ceasefire was negotiated in 1996, granting Chechnya de facto independence.",
    parties: ["Russia", "Chechen Republic of Ichkeria"],
    status: "Ended"
  },
  {
    id: 5,
    name: "Second Chechen War",
    country: "Russia",
    region: "Europe",
    lat: 43.3, lng: 45.7,
    startYear: 1999, endYear: 2009,
    type: "Insurgency",
    fatalities: 25000,
    severity: 4,
    description: "Russia re-invaded Chechnya following apartment bombings in Moscow and an incursion into Dagestan. The campaign was far more successful for Russia, destroying Grozny and eventually establishing Chechen control under pro-Moscow figures. Insurgency continued for years after the main combat phase.",
    parties: ["Russia", "Chechen rebels", "Islamist fighters"],
    status: "Ended"
  },
  {
    id: 6,
    name: "Nagorno-Karabakh Conflicts",
    country: "Azerbaijan / Armenia",
    region: "Europe",
    lat: 40.1, lng: 46.7,
    startYear: 1991, endYear: 2023,
    type: "Interstate War",
    fatalities: 35000,
    severity: 4,
    description: "Decades of conflict over the disputed Nagorno-Karabakh enclave between Armenia and Azerbaijan, including the 1991-1994 war, the 2016 Four-Day War, and the 2020 Second Nagorno-Karabakh War in which Azerbaijan reclaimed most territory. Azerbaijan conducted a final military operation in September 2023, leading to the dissolution of the Armenian statelet.",
    parties: ["Azerbaijan", "Armenia", "Russia (peacekeepers)"],
    status: "Ended"
  },
  {
    id: 7,
    name: "Troubles — Northern Ireland",
    country: "United Kingdom",
    region: "Europe",
    lat: 54.6, lng: -5.9,
    startYear: 1968, endYear: 1998,
    type: "Insurgency",
    fatalities: 3500,
    severity: 3,
    description: "A decades-long ethno-nationalist conflict between largely Catholic Irish nationalists seeking reunification with Ireland and largely Protestant unionists wishing to remain part of the United Kingdom. The conflict involved paramilitaries, security forces, and caused over 3,500 deaths before the Good Friday Agreement brought peace.",
    parties: ["IRA", "UVF", "British Army", "RUC", "Irish Government"],
    status: "Ended"
  },

  // ============================================================
  // MIDDLE EAST
  // ============================================================
  {
    id: 8,
    name: "Syria Civil War",
    country: "Syria",
    region: "Middle East",
    lat: 34.8, lng: 38.9,
    startYear: 2011, endYear: 2024,
    type: "Civil War",
    fatalities: 580000,
    severity: 5,
    description: "Sparked by Arab Spring protests, the conflict escalated into a devastating multi-sided civil war involving the Assad government, rebel factions, Kurdish forces, ISIS, and foreign powers including Russia, Iran, Turkey, and the United States. Chemical weapons were used multiple times. Over 13 million people were displaced.",
    parties: ["Syrian Government", "FSA rebels", "HTS", "SDF/YPG", "ISIS", "Russia", "Iran", "Turkey", "USA"],
    status: "Ended"
  },
  {
    id: 9,
    name: "Yemen Civil War",
    country: "Yemen",
    region: "Middle East",
    lat: 15.4, lng: 45.5,
    startYear: 2015, endYear: null,
    type: "Civil War",
    fatalities: 377000,
    severity: 5,
    description: "Yemen's civil war began when Houthi forces seized the capital Sanaa in 2014-2015, prompting a Saudi-led coalition intervention. The conflict has created one of the world's worst humanitarian crises, with millions facing famine and cholera outbreaks. The Houthis expanded the conflict by attacking Red Sea shipping in 2023-2024.",
    parties: ["Houthis (Ansarallah)", "Saudi-led Coalition", "Yemeni Government", "STC", "USA", "Iran"],
    status: "Ongoing"
  },
  {
    id: 10,
    name: "Israel-Gaza War",
    country: "Israel / Palestine",
    region: "Middle East",
    lat: 31.4, lng: 34.3,
    startYear: 2023, endYear: null,
    type: "Interstate War",
    fatalities: 52000,
    severity: 5,
    description: "Hamas launched a devastating surprise attack on southern Israel on October 7, 2023, killing over 1,200 Israelis and taking 250 hostages. Israel's subsequent military campaign in Gaza has killed tens of thousands of Palestinians and triggered a catastrophic humanitarian crisis. The conflict sparked regional escalation including Hezbollah fighting in Lebanon.",
    parties: ["Israel", "Hamas", "Palestinian Islamic Jihad", "Hezbollah", "Iran"],
    status: "Ongoing"
  },
  {
    id: 11,
    name: "Israel-Palestine Conflict",
    country: "Israel / Palestine",
    region: "Middle East",
    lat: 32.0, lng: 35.2,
    startYear: 1948, endYear: null,
    type: "Interstate War",
    fatalities: 115000,
    severity: 5,
    description: "A century-long conflict over land and national identity, involving multiple Arab-Israeli wars, the Palestinian refugee crisis, Israeli occupation of the West Bank and Gaza, the Oslo peace process, and repeated cycles of violence. The dispute remains one of the world's most intractable conflicts.",
    parties: ["Israel", "Palestinian factions", "Arab states"],
    status: "Ongoing"
  },
  {
    id: 12,
    name: "Iran-Iraq War",
    country: "Iran / Iraq",
    region: "Middle East",
    lat: 32.0, lng: 47.0,
    startYear: 1980, endYear: 1988,
    type: "Interstate War",
    fatalities: 1000000,
    severity: 5,
    description: "One of the 20th century's bloodiest wars, begun when Saddam Hussein's Iraq invaded Iran following the Islamic Revolution. The war featured trench warfare, chemical weapons use, and massive casualties on both sides before ending in a UN-brokered ceasefire with no territorial changes.",
    parties: ["Iraq", "Iran"],
    status: "Ended"
  },
  {
    id: 13,
    name: "Gulf War",
    country: "Kuwait / Iraq",
    region: "Middle East",
    lat: 29.3, lng: 47.7,
    startYear: 1990, endYear: 1991,
    type: "Interstate War",
    fatalities: 35000,
    severity: 4,
    description: "Iraq's invasion and annexation of Kuwait in August 1990 triggered a US-led coalition response. Operation Desert Storm in January-February 1991 rapidly expelled Iraqi forces from Kuwait with overwhelming air and ground power. Iraq's military was badly degraded and post-war sanctions were imposed.",
    parties: ["Iraq", "US-led Coalition", "Kuwait"],
    status: "Ended"
  },
  {
    id: 14,
    name: "Iraq War",
    country: "Iraq",
    region: "Middle East",
    lat: 33.3, lng: 44.4,
    startYear: 2003, endYear: 2011,
    type: "Military Intervention",
    fatalities: 460000,
    severity: 5,
    description: "The US-led coalition invaded Iraq in March 2003, overthrowing Saddam Hussein within weeks. The subsequent occupation was met with a brutal insurgency, sectarian civil war, and the rise of Al-Qaeda in Iraq. The conflict destabilized the entire region and contributed to the conditions that created ISIS.",
    parties: ["USA", "UK", "Coalition", "Iraq", "Sunni insurgents", "Al-Qaeda in Iraq", "Shia militias"],
    status: "Ended"
  },
  {
    id: 15,
    name: "ISIS / ISIL Caliphate",
    country: "Iraq / Syria",
    region: "Middle East",
    lat: 36.3, lng: 43.1,
    startYear: 2013, endYear: 2019,
    type: "Terrorism",
    fatalities: 80000,
    severity: 5,
    description: "The Islamic State seized vast territory across Iraq and Syria in 2014, declaring a caliphate. It controlled millions of people under brutal rule, conducted mass executions, destroyed antiquities, and inspired global terror attacks. A US-led coalition and local forces gradually dismantled the caliphate by 2019.",
    parties: ["ISIS", "Iraq", "Syria", "USA-led Coalition", "Kurds", "Iran"],
    status: "Ended"
  },
  {
    id: 16,
    name: "Lebanese Civil War",
    country: "Lebanon",
    region: "Middle East",
    lat: 33.9, lng: 35.5,
    startYear: 1975, endYear: 1990,
    type: "Civil War",
    fatalities: 150000,
    severity: 5,
    description: "A devastating 15-year civil war involving Lebanese militias, the PLO, Syria, Israel, and Western peacekeepers. The war featured multiple massacres, hostage-takings, and foreign interventions. The Taif Agreement ended major fighting but left deep sectarian divisions that persist to this day.",
    parties: ["Christian militias", "PLO", "Shia militias", "Syria", "Israel"],
    status: "Ended"
  },
  {
    id: 17,
    name: "Afghanistan War (US-led)",
    country: "Afghanistan",
    region: "Middle East",
    lat: 33.9, lng: 67.7,
    startYear: 2001, endYear: 2021,
    type: "Military Intervention",
    fatalities: 241000,
    severity: 5,
    description: "Following the 9/11 attacks, the US and allies invaded Afghanistan to dismantle Al-Qaeda and topple the Taliban regime. Despite initial success, the Taliban waged an insurgency for 20 years. The US withdrew in August 2021, and the Taliban swiftly retook control of the country.",
    parties: ["USA", "NATO", "Afghan Government", "Taliban", "Al-Qaeda"],
    status: "Ended"
  },
  {
    id: 18,
    name: "Afghan Civil War",
    country: "Afghanistan",
    region: "Middle East",
    lat: 34.5, lng: 69.2,
    startYear: 2021, endYear: null,
    type: "Civil War",
    fatalities: 15000,
    severity: 4,
    description: "Following the Taliban's return to power after the US withdrawal, armed resistance groups including the National Resistance Front have continued fighting. ISIS-K (Khorasan Province) has carried out major attacks against Taliban forces and civilian targets. The country faces humanitarian collapse.",
    parties: ["Taliban", "NRF", "ISIS-K"],
    status: "Ongoing"
  },
  {
    id: 19,
    name: "Kurdish-Turkish Conflict",
    country: "Turkey",
    region: "Middle East",
    lat: 37.9, lng: 40.6,
    startYear: 1984, endYear: null,
    type: "Insurgency",
    fatalities: 45000,
    severity: 4,
    description: "The PKK (Kurdistan Workers' Party) launched an armed insurgency for Kurdish autonomy in Turkey in 1984. Despite multiple ceasefires and peace negotiations, the conflict has continued for four decades, killing over 45,000 people. Turkey conducts regular military operations in northern Iraq and Syria targeting PKK bases.",
    parties: ["Turkey", "PKK", "HPG"],
    status: "Ongoing"
  },
  {
    id: 20,
    name: "Saudi Arabia-Yemen Houthi Conflict",
    country: "Saudi Arabia",
    region: "Middle East",
    lat: 24.7, lng: 46.7,
    startYear: 2015, endYear: null,
    type: "Interstate War",
    fatalities: 150000,
    severity: 4,
    description: "Saudi Arabia and its coalition entered Yemen's civil war in 2015 to restore the internationally recognized government against Houthi forces. The war has become a quagmire, with Houthis extending drone and missile attacks to Saudi Arabia and international shipping in the Red Sea.",
    parties: ["Saudi Arabia", "UAE", "Houthis", "USA", "UK"],
    status: "Ongoing"
  },

  // ============================================================
  // AFRICA
  // ============================================================
  {
    id: 21,
    name: "Rwandan Genocide",
    country: "Rwanda",
    region: "Africa",
    lat: -1.9, lng: 29.9,
    startYear: 1994, endYear: 1994,
    type: "Genocide",
    fatalities: 800000,
    severity: 5,
    description: "In just 100 days between April and July 1994, an estimated 500,000–800,000 Tutsi and moderate Hutu were systematically murdered by Hutu extremists. The international community's failure to intervene became a defining case study in genocide prevention. The RPF eventually ended the genocide.",
    parties: ["Hutu Interahamwe", "Tutsi RPF", "Rwandan Government forces"],
    status: "Ended"
  },
  {
    id: 22,
    name: "Darfur Conflict",
    country: "Sudan",
    region: "Africa",
    lat: 13.8, lng: 24.9,
    startYear: 2003, endYear: null,
    type: "Genocide",
    fatalities: 400000,
    severity: 5,
    description: "The Sudanese government and Arab Janjaweed militias conducted a systematic campaign against non-Arab populations in Darfur, western Sudan. The conflict, described as genocide by the US government, caused massive displacement and casualties. The ICC issued an arrest warrant for President Bashir in 2009.",
    parties: ["Sudan Armed Forces", "Janjaweed/RSF", "SLA", "JEM", "Non-Arab ethnic groups"],
    status: "Ongoing"
  },
  {
    id: 23,
    name: "Sudan Civil War 2023",
    country: "Sudan",
    region: "Africa",
    lat: 15.6, lng: 32.5,
    startYear: 2023, endYear: null,
    type: "Civil War",
    fatalities: 30000,
    severity: 5,
    description: "Fighting erupted in April 2023 between the Sudanese Armed Forces (SAF) and the Rapid Support Forces (RSF) paramilitary, previously allied in the 2021 coup. The conflict has devastated Khartoum and spread to Darfur, creating what the UN called the world's largest humanitarian and displacement crisis.",
    parties: ["Sudanese Armed Forces", "Rapid Support Forces (RSF)"],
    status: "Ongoing"
  },
  {
    id: 24,
    name: "Somali Civil War",
    country: "Somalia",
    region: "Africa",
    lat: 2.0, lng: 45.3,
    startYear: 1991, endYear: null,
    type: "Civil War",
    fatalities: 500000,
    severity: 5,
    description: "Following the collapse of the Barre regime in 1991, Somalia descended into prolonged civil war, clan fighting, and state failure. Al-Shabaab Islamist insurgency remains active despite international peacekeeping missions. Multiple famines caused by conflict and drought killed hundreds of thousands.",
    parties: ["Al-Shabaab", "Federal Government", "Clan militias", "AMISOM/ATMIS", "USA"],
    status: "Ongoing"
  },
  {
    id: 25,
    name: "Tigray War",
    country: "Ethiopia",
    region: "Africa",
    lat: 14.0, lng: 38.5,
    startYear: 2020, endYear: 2022,
    type: "Civil War",
    fatalities: 300000,
    severity: 5,
    description: "War between Ethiopian federal forces and the Tigray People's Liberation Front (TPLF), involving Eritrean forces. The conflict featured mass atrocities, famine conditions affecting millions, and large-scale displacement. A peace agreement was signed in November 2022 but fragile.",
    parties: ["Ethiopia", "Eritrea", "TPLF/TDF", "Amhara forces"],
    status: "Ended"
  },
  {
    id: 26,
    name: "DR Congo Conflicts",
    country: "DR Congo",
    region: "Africa",
    lat: -4.3, lng: 15.3,
    startYear: 1996, endYear: null,
    type: "Civil War",
    fatalities: 6000000,
    severity: 5,
    description: "Two Congo Wars (1996-1997, 1998-2003) and persistent insurgencies have made the DRC the site of the world's deadliest conflict since WWII. Over 120 armed groups operate in eastern Congo. The M23 rebel group backed by Rwanda re-emerged in 2022 and captured Goma in 2024.",
    parties: ["DRC Army", "M23/Rwanda", "FDLR", "ADF", "MONUSCO", "Uganda"],
    status: "Ongoing"
  },
  {
    id: 27,
    name: "Central African Republic Conflict",
    country: "Central African Republic",
    region: "Africa",
    lat: 6.6, lng: 20.9,
    startYear: 2012, endYear: null,
    type: "Civil War",
    fatalities: 50000,
    severity: 4,
    description: "The CAR has been engulfed in conflict since Seleka coalition rebels overthrew President Bozizé in 2013. Subsequent fighting between Seleka and anti-Balaka Christian militias caused mass atrocities. Russian Wagner Group forces arrived in 2018, helping the government gain ground while committing abuses.",
    parties: ["CAR Government", "Seleka/ex-Seleka", "Anti-Balaka", "Wagner Group/Russia", "MINUSCA"],
    status: "Ongoing"
  },
  {
    id: 28,
    name: "South Sudan Civil War",
    country: "South Sudan",
    region: "Africa",
    lat: 6.9, lng: 31.3,
    startYear: 2013, endYear: 2018,
    type: "Civil War",
    fatalities: 400000,
    severity: 5,
    description: "Just two years after independence, South Sudan descended into civil war when President Kiir dismissed Vice President Machar, triggering fighting between Dinka and Nuer ethnic factions. The conflict caused famine, mass displacement, and atrocities. A peace deal was signed in 2018 but remains fragile.",
    parties: ["SPLM/A", "SPLM/A-IO", "Various armed groups"],
    status: "Ended"
  },
  {
    id: 29,
    name: "Mali Conflict",
    country: "Mali",
    region: "Africa",
    lat: 17.5, lng: -3.9,
    startYear: 2012, endYear: null,
    type: "Insurgency",
    fatalities: 15000,
    severity: 4,
    description: "A Tuareg rebellion and Islamist insurgency engulfed northern Mali in 2012. French Operation Serval (later Barkhane) halted Islamist advance but the insurgency continued for over a decade across the Sahel. After military coups, Mali expelled French forces and invited Wagner Group in 2021.",
    parties: ["Mali Government", "JNIM/Al-Qaeda", "ISGS/ISIS", "France/Barkhane", "Wagner Group", "MINUSMA"],
    status: "Ongoing"
  },
  {
    id: 30,
    name: "Mozambique Insurgency",
    country: "Mozambique",
    region: "Africa",
    lat: -13.3, lng: 35.3,
    startYear: 2017, endYear: null,
    type: "Insurgency",
    fatalities: 5000,
    severity: 3,
    description: "An Islamist insurgency in Cabo Delgado province in northern Mozambique began in 2017, linked to ISIS. The insurgents captured the port town of Mocímboa da Praia and threatened major natural gas projects. SADC forces and Rwandan troops deployed in 2021 to push back the insurgency.",
    parties: ["Ansar al-Sunna/ISIS", "Mozambique Armed Forces", "SADC Mission", "Rwanda", "DYCK Advisory Group"],
    status: "Ongoing"
  },
  {
    id: 31,
    name: "Boko Haram Insurgency",
    country: "Nigeria",
    region: "Africa",
    lat: 11.8, lng: 13.2,
    startYear: 2009, endYear: null,
    type: "Terrorism",
    fatalities: 40000,
    severity: 4,
    description: "Boko Haram launched an insurgency against the Nigerian government in 2009, seizing territory across northeast Nigeria and pledging allegiance to ISIS in 2015. The group became notorious for mass kidnappings, including the Chibok schoolgirls abduction. Factionalism weakened but did not end the insurgency.",
    parties: ["Boko Haram", "ISWAP", "Nigeria", "Cameroon", "Niger", "Chad", "MNJTF"],
    status: "Ongoing"
  },
  {
    id: 32,
    name: "Ethiopian-Eritrean War",
    country: "Ethiopia / Eritrea",
    region: "Africa",
    lat: 14.9, lng: 38.9,
    startYear: 1998, endYear: 2000,
    type: "Interstate War",
    fatalities: 80000,
    severity: 4,
    description: "A brutal interstate war fought over disputed border territories between the former allies Ethiopia and Eritrea. Despite a peace agreement in 2000, the border remained tense until a normalization agreement in 2018. Both sides deployed massive ground forces in set-piece battles reminiscent of WWI.",
    parties: ["Ethiopia", "Eritrea"],
    status: "Ended"
  },
  {
    id: 33,
    name: "Libya Civil Wars",
    country: "Libya",
    region: "Africa",
    lat: 32.9, lng: 13.2,
    startYear: 2011, endYear: null,
    type: "Civil War",
    fatalities: 30000,
    severity: 4,
    description: "NATO intervention in 2011 helped rebel forces overthrow Gaddafi, but Libya subsequently fragmented between rival governments and militias. A second civil war erupted in 2014, with the UN-backed government in Tripoli facing the Tobruk-based parliament backed by General Haftar's LNA. A ceasefire in 2020 created an uneasy stalemate.",
    parties: ["GNU/GNA", "LNA (Haftar)", "Various militias", "Turkey", "Russia/Wagner", "UAE", "Egypt"],
    status: "Ongoing"
  },
  {
    id: 34,
    name: "Angolan Civil War",
    country: "Angola",
    region: "Africa",
    lat: -11.2, lng: 17.9,
    startYear: 1975, endYear: 2002,
    type: "Civil War",
    fatalities: 500000,
    severity: 5,
    description: "One of the Cold War's most destructive proxy conflicts, pitting the MPLA government (backed by USSR and Cuba) against UNITA rebels (backed by the US and South Africa). Peace agreements collapsed multiple times. A final peace accord in 2002, following UNITA leader Savimbi's death, ended the 27-year war.",
    parties: ["MPLA", "UNITA", "Cuba", "South Africa", "USA"],
    status: "Ended"
  },
  {
    id: 35,
    name: "Sierra Leone Civil War",
    country: "Sierra Leone",
    region: "Africa",
    lat: 8.5, lng: -13.2,
    startYear: 1991, endYear: 2002,
    type: "Civil War",
    fatalities: 50000,
    severity: 4,
    description: "The Revolutionary United Front (RUF) conducted a brutal civil war marked by systematic amputations, child soldiers, and diamond mining to fund operations. A UK military intervention and UN peacekeeping force eventually helped end the conflict. The war became a defining moment in international discussions on atrocity crimes.",
    parties: ["Sierra Leone Government", "RUF", "ECOMOG", "UK", "UNAMSIL"],
    status: "Ended"
  },
  {
    id: 36,
    name: "Mozambique Civil War",
    country: "Mozambique",
    region: "Africa",
    lat: -18.7, lng: 35.5,
    startYear: 1977, endYear: 1992,
    type: "Civil War",
    fatalities: 1000000,
    severity: 5,
    description: "A devastating 15-year civil war between the FRELIMO government and RENAMO rebels, fueled by Cold War dynamics and South African destabilization. The conflict caused immense civilian suffering including deliberate attacks on hospitals and schools. A Rome peace agreement in 1992 ended the fighting.",
    parties: ["FRELIMO", "RENAMO", "South Africa", "Zimbabwe"],
    status: "Ended"
  },

  // ============================================================
  // ASIA
  // ============================================================
  {
    id: 37,
    name: "Kashmir Conflict",
    country: "India / Pakistan",
    region: "Asia",
    lat: 34.1, lng: 74.8,
    startYear: 1989, endYear: null,
    type: "Insurgency",
    fatalities: 47000,
    severity: 4,
    description: "An insurgency in the Indian-administered Jammu and Kashmir has run since 1989, backed by Pakistan. Multiple India-Pakistan military crises over Kashmir, including the 1999 Kargil War, have brought nuclear-armed rivals to the brink. India revoked Kashmir's special status in 2019, increasing tensions.",
    parties: ["India", "Pakistan", "Kashmiri militants", "Hizbul Mujahideen", "Lashkar-e-Taiba"],
    status: "Ongoing"
  },
  {
    id: 38,
    name: "Myanmar Civil War",
    country: "Myanmar",
    region: "Asia",
    lat: 21.9, lng: 96.1,
    startYear: 2021, endYear: null,
    type: "Civil War",
    fatalities: 50000,
    severity: 5,
    description: "Following the military coup of February 1, 2021, a nationwide resistance movement emerged. The People's Defence Force and ethnic armed organizations launched a coordinated military offensive (Operation 1027) in late 2023 that seized major cities from the junta. Myanmar is experiencing its worst conflict in decades.",
    parties: ["Myanmar Junta/SAC", "NUG/PDF", "MNDAA", "TNLA", "AA", "KIA", "KNU"],
    status: "Ongoing"
  },
  {
    id: 39,
    name: "Rohingya Genocide",
    country: "Myanmar",
    region: "Asia",
    lat: 20.4, lng: 92.9,
    startYear: 2017, endYear: 2017,
    type: "Genocide",
    fatalities: 25000,
    severity: 5,
    description: "Myanmar's military launched a brutal crackdown on the Rohingya Muslim minority in Rakhine state in August 2017, described by the UN as a textbook case of ethnic cleansing. Over 700,000 Rohingya fled to Bangladesh in months. The Gambia brought genocide charges against Myanmar at the International Court of Justice.",
    parties: ["Myanmar Military", "Arakan Rohingya Salvation Army", "Rohingya population"],
    status: "Ended"
  },
  {
    id: 40,
    name: "Sri Lankan Civil War",
    country: "Sri Lanka",
    region: "Asia",
    lat: 8.5, lng: 80.8,
    startYear: 1983, endYear: 2009,
    type: "Civil War",
    fatalities: 100000,
    severity: 5,
    description: "The Tamil Tigers (LTTE) fought for an independent Tamil homeland in northern Sri Lanka, pioneering suicide bombing tactics. The conflict lasted 26 years and was marked by numerous massacres and atrocities by both sides. The Sri Lankan military decisively defeated the LTTE in May 2009 in what human rights groups called a bloodbath.",
    parties: ["Sri Lanka", "LTTE (Tamil Tigers)"],
    status: "Ended"
  },
  {
    id: 41,
    name: "Philippine Insurgencies",
    country: "Philippines",
    region: "Asia",
    lat: 7.1, lng: 124.2,
    startYear: 1969, endYear: null,
    type: "Insurgency",
    fatalities: 120000,
    severity: 4,
    description: "The Philippines has faced dual communist (NPA) and Islamist (MILF, ASG) insurgencies for decades. The Mindanao insurgency led to a peace framework with the MILF and creation of the Bangsamoro Autonomous Region in 2019. The communist NPA insurgency continues in rural areas.",
    parties: ["Philippines", "NPA/CPP", "MILF", "MNLF", "Abu Sayyaf", "ISIS-Philippines"],
    status: "Ongoing"
  },
  {
    id: 42,
    name: "India-Pakistan Wars",
    country: "India / Pakistan",
    region: "Asia",
    lat: 30.3, lng: 73.0,
    startYear: 1947, endYear: 1999,
    type: "Interstate War",
    fatalities: 100000,
    severity: 5,
    description: "India and Pakistan have fought four major wars (1947, 1965, 1971, 1999 Kargil) since partition. The 1971 war resulted in the independence of Bangladesh and Pakistan's most decisive defeat. The 1999 Kargil conflict was the first war between declared nuclear-armed states.",
    parties: ["India", "Pakistan"],
    status: "Ended"
  },
  {
    id: 43,
    name: "North Korea-South Korea (Ongoing)",
    country: "North Korea / South Korea",
    region: "Asia",
    lat: 38.3, lng: 127.5,
    startYear: 1953, endYear: null,
    type: "Frozen Conflict",
    fatalities: 5000000,
    severity: 5,
    description: "The Korean War (1950-1953) ended with an armistice, not a peace treaty, leaving the peninsula technically at war. The DMZ remains one of the world's most heavily militarized borders. North Korea has conducted multiple nuclear tests and missile launches, while limited skirmishes occur periodically at the border.",
    parties: ["North Korea", "South Korea", "USA", "China"],
    status: "Frozen"
  },
  {
    id: 44,
    name: "Cambodian-Vietnamese War",
    country: "Cambodia / Vietnam",
    region: "Asia",
    lat: 12.5, lng: 104.9,
    startYear: 1975, endYear: 1991,
    type: "Interstate War",
    fatalities: 50000,
    severity: 4,
    description: "Vietnam invaded Cambodia in December 1978, toppling the Khmer Rouge regime and ending the genocide. Vietnamese forces occupied Cambodia until 1989, fighting a protracted guerrilla war against Khmer Rouge remnants backed by China and the West. UN peacekeeping and elections in 1993 eventually stabilized the country.",
    parties: ["Vietnam", "Cambodia", "Khmer Rouge", "China"],
    status: "Ended"
  },
  {
    id: 45,
    name: "Cambodian Genocide",
    country: "Cambodia",
    region: "Asia",
    lat: 12.0, lng: 104.9,
    startYear: 1975, endYear: 1979,
    type: "Genocide",
    fatalities: 2000000,
    severity: 5,
    description: "The Khmer Rouge under Pol Pot executed a radical agrarian revolution that killed between 1.5 and 2 million Cambodians through execution, forced labor, starvation, and disease — approximately 25% of Cambodia's population. Cities were forcibly evacuated, intellectuals were killed, and a reign of terror lasted four years.",
    parties: ["Khmer Rouge", "Cambodian population"],
    status: "Ended"
  },

  // ============================================================
  // AMERICAS
  // ============================================================
  {
    id: 46,
    name: "Colombian Armed Conflict",
    country: "Colombia",
    region: "Americas",
    lat: 4.1, lng: -72.9,
    startYear: 1964, endYear: null,
    type: "Insurgency",
    fatalities: 220000,
    severity: 4,
    description: "Colombia's armed conflict involves FARC guerrillas, ELN, paramilitary groups, and drug cartels. A 2016 peace agreement with FARC ended that insurgency but FARC dissidents and ELN continued fighting. The conflict has involved mass displacement, disappearances, and recruitment of child soldiers.",
    parties: ["Colombia", "FARC-EP/dissidents", "ELN", "AUC paramilitaries", "Clan del Golfo"],
    status: "Ongoing"
  },
  {
    id: 47,
    name: "US Invasion of Panama",
    country: "Panama",
    region: "Americas",
    lat: 8.9, lng: -79.5,
    startYear: 1989, endYear: 1990,
    type: "Military Intervention",
    fatalities: 3000,
    severity: 2,
    description: "Operation Just Cause saw 27,000 US troops invade Panama in December 1989 to overthrow Manuel Noriega following elections he voided and amid drug trafficking charges. Noriega surrendered in January 1990. The invasion drew widespread international condemnation despite ousting an authoritarian ruler.",
    parties: ["USA", "Panama Defense Forces"],
    status: "Ended"
  },
  {
    id: 48,
    name: "Falklands War",
    country: "Argentina / UK",
    region: "Americas",
    lat: -51.7, lng: -59.5,
    startYear: 1982, endYear: 1982,
    type: "Interstate War",
    fatalities: 900,
    severity: 2,
    description: "Argentina seized the British Falkland Islands in April 1982. The UK dispatched a task force that recaptured the islands after 74 days of fighting. The British victory ended the Argentine junta's rule and strengthened Margaret Thatcher's political position.",
    parties: ["Argentina", "United Kingdom"],
    status: "Ended"
  },
  {
    id: 49,
    name: "El Salvador Civil War",
    country: "El Salvador",
    region: "Americas",
    lat: 13.7, lng: -88.9,
    startYear: 1979, endYear: 1992,
    type: "Civil War",
    fatalities: 75000,
    severity: 4,
    description: "A civil war between the US-backed military government and the FMLN leftist guerrilla coalition left 75,000 dead and 1 million displaced. The conflict featured death squads, the murder of Archbishop Romero, and the El Mozote massacre. UN-brokered peace accords were signed in January 1992.",
    parties: ["El Salvador Government", "FMLN", "USA", "Cuba"],
    status: "Ended"
  },
  {
    id: 50,
    name: "Guatemala Civil War",
    country: "Guatemala",
    region: "Americas",
    lat: 15.5, lng: -90.3,
    startYear: 1960, endYear: 1996,
    type: "Civil War",
    fatalities: 200000,
    severity: 5,
    description: "Guatemala's 36-year civil war between the US-backed government and leftist guerrillas was marked by genocide against indigenous Maya communities. The 1981-1983 period under General Ríos Montt saw mass massacres in highland villages. A UN commission later attributed 93% of atrocities to state forces.",
    parties: ["Guatemala Government", "URNG guerrillas", "USA"],
    status: "Ended"
  },
  {
    id: 51,
    name: "Nicaragua Contra War",
    country: "Nicaragua",
    region: "Americas",
    lat: 12.9, lng: -85.2,
    startYear: 1981, endYear: 1990,
    type: "Civil War",
    fatalities: 30000,
    severity: 3,
    description: "The CIA-backed Contra insurgency fought against the Sandinista government following their 1979 revolution. The Iran-Contra affair exposed illegal US arms sales funding the Contras. The war ended with free elections in 1990 that the Sandinistas lost.",
    parties: ["Sandinista Government", "Contras", "USA"],
    status: "Ended"
  },
  {
    id: 52,
    name: "Haiti Political Violence",
    country: "Haiti",
    region: "Americas",
    lat: 18.9, lng: -72.3,
    startYear: 2021, endYear: null,
    type: "Civil War",
    fatalities: 8000,
    severity: 4,
    description: "Following the assassination of President Moïse in July 2021, powerful gangs seized control of large swathes of Haiti. Gang leader Barbecue and the Viv Ansanm coalition launched coordinated attacks in 2024, taking the airport and prisons. A Kenyan-led multinational security mission deployed in 2024.",
    parties: ["Haitian gangs/Viv Ansanm", "Haitian National Police", "MSS (Kenya-led)"],
    status: "Ongoing"
  },

  // ============================================================
  // SOUTH / SOUTHEAST ASIA
  // ============================================================
  {
    id: 53,
    name: "Vietnam War",
    country: "Vietnam",
    region: "Asia",
    lat: 16.5, lng: 107.6,
    startYear: 1955, endYear: 1975,
    type: "Civil War",
    fatalities: 3500000,
    severity: 5,
    description: "The Cold War's defining proxy conflict, pitting communist North Vietnam and Viet Cong against South Vietnam and the United States. Over 58,000 Americans and up to 3.5 million Vietnamese died. The fall of Saigon in April 1975 unified Vietnam under communist rule.",
    parties: ["North Vietnam/NVA", "South Vietnam", "USA", "Viet Cong", "China", "USSR"],
    status: "Ended"
  },
  {
    id: 54,
    name: "Bangladesh Liberation War",
    country: "Bangladesh / Pakistan",
    region: "Asia",
    lat: 23.7, lng: 90.4,
    startYear: 1971, endYear: 1971,
    type: "Interstate War",
    fatalities: 3000000,
    severity: 5,
    description: "Pakistan's military crackdown on Bengali nationalists in East Pakistan triggered a genocide and a war for independence. India intervened militarily in December 1971, decisively defeating Pakistani forces. Bangladesh became independent, and the conflict killed an estimated 300,000 to 3 million people.",
    parties: ["Pakistan", "Bangladesh/Mukti Bahini", "India"],
    status: "Ended"
  },
  {
    id: 55,
    name: "Timor-Leste Independence War",
    country: "Indonesia / Timor-Leste",
    region: "Asia",
    lat: -8.9, lng: 125.7,
    startYear: 1975, endYear: 1999,
    type: "Civil War",
    fatalities: 180000,
    severity: 5,
    description: "Indonesia invaded East Timor in 1975, days after Portugal's colonial withdrawal. The ensuing 24-year occupation caused the deaths of an estimated 100,000-180,000 Timorese through violence, famine, and disease. A 1999 independence referendum was followed by pro-Indonesia militia massacres before UN intervention.",
    parties: ["Indonesia", "Fretilin/Falintil", "UN"],
    status: "Ended"
  },

  // ============================================================
  // ADDITIONAL CONFLICTS
  // ============================================================
  {
    id: 56,
    name: "Xinjiang Repression",
    country: "China",
    region: "Asia",
    lat: 43.8, lng: 87.6,
    startYear: 2017, endYear: null,
    type: "Genocide",
    fatalities: 0,
    severity: 4,
    description: "China has subjected Uyghurs and other Muslim minorities in Xinjiang to mass detention in 'political re-education camps,' mass surveillance, forced labor, and cultural destruction. The US government and several European parliaments have designated this a genocide or crimes against humanity. China denies the characterizations.",
    parties: ["China", "Uyghur population"],
    status: "Ongoing"
  },
  {
    id: 57,
    name: "Pakistan-Afghanistan Border Conflict",
    country: "Pakistan",
    region: "Asia",
    lat: 33.7, lng: 70.1,
    startYear: 2001, endYear: null,
    type: "Insurgency",
    fatalities: 70000,
    severity: 4,
    description: "Pakistan has battled the Tehrik-i-Taliban Pakistan (TTP) along the Afghan border since 2001. Cross-border attacks, drone strikes, and military operations have caused tens of thousands of deaths. Attacks sharply escalated after the Taliban takeover of Afghanistan as TTP used Afghan territory for operations.",
    parties: ["Pakistan", "TTP", "Afghan Taliban", "USA"],
    status: "Ongoing"
  },
  {
    id: 58,
    name: "Nagaland Insurgency",
    country: "India",
    region: "Asia",
    lat: 26.1, lng: 94.6,
    startYear: 1954, endYear: null,
    type: "Insurgency",
    fatalities: 30000,
    severity: 2,
    description: "India's oldest insurgency, the Naga struggle for independence in northeastern India has been ongoing since the 1950s. A framework peace agreement was reached with the NSCN-IM in 2015 but a final settlement has not been concluded. The conflict is at low intensity with periodic violations.",
    parties: ["India", "NSCN-IM", "NSCN-K"],
    status: "Ongoing"
  },
  {
    id: 59,
    name: "Balochistan Insurgency",
    country: "Pakistan",
    region: "Asia",
    lat: 28.5, lng: 65.8,
    startYear: 2003, endYear: null,
    type: "Insurgency",
    fatalities: 20000,
    severity: 3,
    description: "Baloch nationalists have waged an insurgency against the Pakistani state since at least 2003, targeting security forces, Chinese CPEC projects, and state infrastructure. The conflict involves forced disappearances and extrajudicial killings by Pakistani security forces.",
    parties: ["Pakistan", "BLA", "BLF", "BSO"],
    status: "Ongoing"
  },
  {
    id: 60,
    name: "Sudan-South Sudan Border",
    country: "Sudan / South Sudan",
    region: "Africa",
    lat: 10.4, lng: 32.0,
    startYear: 2012, endYear: 2012,
    type: "Interstate War",
    fatalities: 1500,
    severity: 2,
    description: "Fighting over the disputed Heglig oil fields erupted briefly in 2012, with South Sudanese forces briefly seizing the area before withdrawing under international pressure. The unresolved border demarcation and oil revenue sharing disputes continue to cause tensions between the two countries.",
    parties: ["Sudan", "South Sudan"],
    status: "Ended"
  },
  {
    id: 61,
    name: "Ethiopian Civil War (Oromo-Amhara)",
    country: "Ethiopia",
    region: "Africa",
    lat: 9.1, lng: 40.5,
    startYear: 2018, endYear: null,
    type: "Civil War",
    fatalities: 20000,
    severity: 4,
    description: "Following the Tigray War ceasefire, fighting has continued in the Amhara and Oromia regions. The Fano Amhara militia fought against federal forces after the government sought to disarm regional forces in 2023. The OLA/Oromo Liberation Army has also continued fighting in Oromia.",
    parties: ["Ethiopia", "Fano Amhara", "OLA/Oromo Liberation Army"],
    status: "Ongoing"
  },
  {
    id: 62,
    name: "Burkina Faso Insurgency",
    country: "Burkina Faso",
    region: "Africa",
    lat: 12.4, lng: -1.6,
    startYear: 2015, endYear: null,
    type: "Insurgency",
    fatalities: 15000,
    severity: 4,
    description: "Jihadist groups linked to Al-Qaeda (JNIM) and ISIS have spread from Mali into Burkina Faso, capturing large areas of the country and besieging towns. Two military coups in 2022 brought Captain Traoré to power, who expelled French forces and invited Russian Wagner/Africa Corps. Over 2 million are displaced.",
    parties: ["Burkina Faso", "JNIM", "ISGS", "Russia/Africa Corps"],
    status: "Ongoing"
  },
  {
    id: 63,
    name: "Niger / Sahel Jihadist Conflict",
    country: "Niger",
    region: "Africa",
    lat: 17.6, lng: 8.1,
    startYear: 2015, endYear: null,
    type: "Insurgency",
    fatalities: 10000,
    severity: 3,
    description: "Niger has faced escalating jihadist attacks from JNIM and ISGS in the Tillabéri region bordering Mali and Burkina Faso. A military coup in July 2023 led to the expulsion of French and US forces. The Sahel Alliance (Niger, Mali, Burkina Faso) formed to coordinate security but with Russian backing.",
    parties: ["Niger", "JNIM", "ISGS", "Russia"],
    status: "Ongoing"
  },
  {
    id: 64,
    name: "Iraq-Kurdish Conflict",
    country: "Iraq",
    region: "Middle East",
    lat: 36.2, lng: 44.0,
    startYear: 1986, endYear: 1991,
    type: "Genocide",
    fatalities: 182000,
    severity: 5,
    description: "Saddam Hussein's Anfal campaign systematically targeted Kurdish civilians in northern Iraq from 1986-1989 using chemical weapons, including the Halabja massacre of 5,000 in 1988. An estimated 50,000-182,000 Kurds were killed. The campaign is recognized as genocide by international bodies.",
    parties: ["Iraq", "Kurdish population", "Peshmerga"],
    status: "Ended"
  },
  {
    id: 65,
    name: "South Africa Apartheid Conflict",
    country: "South Africa",
    region: "Africa",
    lat: -29.0, lng: 26.0,
    startYear: 1960, endYear: 1994,
    type: "Civil War",
    fatalities: 21000,
    severity: 4,
    description: "The ANC's armed wing Umkhonto we Sizwe and other groups fought the apartheid regime through sabotage, guerrilla warfare, and international pressure campaigns. Political violence between ANC and Inkatha supporters killed thousands. Negotiations ending apartheid and leading to elections in 1994 ended the conflict.",
    parties: ["South Africa", "ANC/MK", "Inkatha", "PAC"],
    status: "Ended"
  },
  {
    id: 66,
    name: "Zimbabwe Crisis",
    country: "Zimbabwe",
    region: "Africa",
    lat: -20.0, lng: 30.0,
    startYear: 2000, endYear: 2017,
    type: "Civil War",
    fatalities: 20000,
    severity: 3,
    description: "Zimbabwe under Mugabe saw violent land seizures from white farmers, political violence against opposition MDC supporters, and the Gukurahundi massacres in Matabeleland (1983-1987) that killed an estimated 20,000. Economic collapse and hyper-inflation triggered mass emigration. Mugabe was ousted in a military coup in 2017.",
    parties: ["ZANU-PF/Mugabe", "MDC opposition", "War veterans"],
    status: "Ended"
  },
  {
    id: 67,
    name: "Liberia Civil Wars",
    country: "Liberia",
    region: "Africa",
    lat: 6.4, lng: -9.4,
    startYear: 1989, endYear: 2003,
    type: "Civil War",
    fatalities: 250000,
    severity: 5,
    description: "Two civil wars (1989-1996, 1999-2003) devastated Liberia under Charles Taylor's rule. Child soldiers, cannibalism, and mass atrocities characterized the conflict. Taylor was later convicted of war crimes by the Special Court for Sierra Leone. West African ECOMOG peacekeepers played a key role.",
    parties: ["NPFL/Charles Taylor", "LURD", "MODEL", "Liberia Government", "ECOMOG"],
    status: "Ended"
  },
  {
    id: 68,
    name: "Congo-Brazzaville Civil War",
    country: "Congo-Brazzaville",
    region: "Africa",
    lat: -4.3, lng: 15.3,
    startYear: 1997, endYear: 1999,
    type: "Civil War",
    fatalities: 10000,
    severity: 3,
    description: "A civil war between President Lissouba and former president Sassou-Nguesso's Cobra militia, backed by Angola and France. Sassou-Nguesso returned to power and fighting eventually ended in 1999 after a peace agreement. The country has remained relatively stable under Sassou-Nguesso's rule.",
    parties: ["Congo Government/Lissouba", "Cobra militia/Sassou-Nguesso", "Angola"],
    status: "Ended"
  },
  {
    id: 69,
    name: "Guinea Civil Unrest",
    country: "Guinea",
    region: "Africa",
    lat: 11.0, lng: -15.0,
    startYear: 2020, endYear: null,
    type: "Civil War",
    fatalities: 2000,
    severity: 2,
    description: "A military coup in September 2021 overthrew President Condé following disputed elections in 2020. Political violence and crackdowns on protesters have caused casualties. The military junta has resisted pressure to restore civilian rule, and violence against opposition continues.",
    parties: ["Guinea Military Junta", "Opposition groups"],
    status: "Ongoing"
  },
  {
    id: 70,
    name: "Iran Green Movement",
    country: "Iran",
    region: "Middle East",
    lat: 35.7, lng: 51.4,
    startYear: 2009, endYear: 2022,
    type: "Civil War",
    fatalities: 1500,
    severity: 2,
    description: "Iran's Green Movement protests in 2009 followed disputed elections, leading to violent crackdowns. The 2019 November protests over fuel prices saw security forces kill hundreds. The 2022 Mahsa Amini protests over mandatory hijab spread across Iran and were met with security force violence killing over 500.",
    parties: ["Iranian Government/IRGC", "Opposition/protesters"],
    status: "Ended"
  },
  {
    id: 71,
    name: "Chechnya-Russia (Chechen Republic Today)",
    country: "Russia",
    region: "Europe",
    lat: 43.2, lng: 45.8,
    startYear: 2007, endYear: null,
    type: "Insurgency",
    fatalities: 3000,
    severity: 2,
    description: "After the two Chechen wars, Kadyrov's security forces conduct ongoing counter-insurgency operations against remaining underground fighters and have been deployed in Syria and Ukraine. Extrajudicial killings and persecution of perceived enemies occur regularly. The region is pacified but under authoritarian control.",
    parties: ["Kadyrovites", "Chechen underground", "Russia"],
    status: "Ongoing"
  },
  {
    id: 72,
    name: "Taiwan Strait Tensions",
    country: "China / Taiwan",
    region: "Asia",
    lat: 23.7, lng: 120.9,
    startYear: 1954, endYear: null,
    type: "Border Conflict",
    fatalities: 2000,
    severity: 4,
    description: "The Taiwan Strait has been a flashpoint since 1949 when the Nationalist government retreated to Taiwan. China considers Taiwan a breakaway province. Military tensions escalated significantly in 2022 after Nancy Pelosi's visit to Taiwan, with China conducting unprecedented military exercises encircling the island. The situation is considered the world's most dangerous potential military flashpoint.",
    parties: ["China", "Taiwan", "USA"],
    status: "Frozen"
  },
  {
    id: 73,
    name: "South China Sea Disputes",
    country: "China / Philippines / Vietnam",
    region: "Asia",
    lat: 15.0, lng: 114.0,
    startYear: 1974, endYear: null,
    type: "Border Conflict",
    fatalities: 1000,
    severity: 3,
    description: "China claims nearly the entire South China Sea through its Nine-Dash Line, conflicting with claims of Vietnam, Philippines, Malaysia, Brunei, and Taiwan. China has built artificial islands with military installations. Incidents with Philippine Coast Guard vessels at Second Thomas Shoal have escalated since 2023.",
    parties: ["China", "Philippines", "Vietnam", "Malaysia", "USA"],
    status: "Ongoing"
  },
  {
    id: 74,
    name: "India-China Border Clash",
    country: "India / China",
    region: "Asia",
    lat: 33.7, lng: 78.7,
    startYear: 2020, endYear: null,
    type: "Border Conflict",
    fatalities: 45,
    severity: 2,
    description: "China and India fought a deadly hand-to-hand clash in Galwan Valley in June 2020, the first fatal India-China border incident since 1975. Both sides have massively increased border infrastructure and troops in the Himalayas since. Despite pullbacks at some friction points, the situation remains tense along the LAC.",
    parties: ["India", "China"],
    status: "Frozen"
  },
  {
    id: 75,
    name: "Venezuela Political Crisis",
    country: "Venezuela",
    region: "Americas",
    lat: 10.5, lng: -66.9,
    startYear: 2019, endYear: null,
    type: "Civil War",
    fatalities: 5000,
    severity: 3,
    description: "Venezuela descended into a political and humanitarian crisis under Maduro's rule, with widespread political violence, gang/colectivo control, and FARC and ELN presence in border regions. Political crackdowns following the disputed 2024 elections led to mass protests and arrests of opposition leaders.",
    parties: ["Maduro Government", "Opposition/Guaidó", "FARC/ELN", "Colectivos"],
    status: "Ongoing"
  }
];
